# Generated by Django 4.0.5 on 2022-06-05 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros_app', '0003_alter_membro_laboratorio_alter_membro_membro_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('turno', models.CharField(max_length=1)),
                ('horario', models.IntegerField()),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membrohorario', to='membros_app.membro')),
            ],
        ),
    ]
