# Generated by Django 4.0.4 on 2022-07-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horario_app', '0001_initial'),
        ('membros_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membrohorario', to='membros_app.membro'),
        ),
    ]
