# Generated by Django 4.0.5 on 2022-06-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario_app', '0002_alter_horario_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.TimeField(),
        ),
    ]
