# Generated by Django 4.0.5 on 2022-06-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario_app', '0004_remove_horario_dia_remove_horario_horario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='dia_semana',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='horario_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='horario_saida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='turno',
            field=models.CharField(blank=True, choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Noturno', 'Noturno')], max_length=50, null=True),
        ),
    ]
