# Generated by Django 4.0.5 on 2022-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horario_app', '0005_horario_dia_semana_horario_horario_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date(dd/mm/2022)'),
        ),
    ]
