# Generated by Django 4.0.5 on 2022-06-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros_app', '0003_alter_membro_laboratorio_alter_membro_membro_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('dataApresentacao', models.DateField()),
                ('descricao', models.CharField(max_length=150)),
                ('autores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoresApresentacao', to='membros_app.membro')),
            ],
        ),
    ]
