# Generated by Django 4.0.4 on 2022-07-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros_app', '0001_initial'),
        ('apresentacao_app', '0001_initial'),
        ('projetos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='autores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoresApresentacao', to='membros_app.membro'),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos_app.projeto'),
        ),
    ]
