# Generated by Django 4.0.5 on 2022-07-16 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0003_alter_docente_formacao'),
        ('apresentacao_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='autores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoresApresentacao', to='usuarios_app.discente'),
        ),
    ]
