# Generated by Django 4.0.5 on 2022-07-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorio_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estagiario', models.CharField(max_length=30)),
                ('orientador', models.CharField(max_length=30)),
                ('supervisor', models.CharField(max_length=30)),
                ('atividade', models.URLField()),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio_app.lab')),
            ],
        ),
    ]
