# Generated by Django 4.0.4 on 2022-07-08 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membros_app', '0001_initial'),
        ('estagio_app', '0002_alter_estagio_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='estagiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membro_estagiario', to='membros_app.membro'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membro_orientador', to='membros_app.membro'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membro_supervisor', to='membros_app.membro'),
        ),
    ]
