# Generated by Django 4.0.4 on 2022-07-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_app', '0002_initial'),
        ('estagio_app', '0003_alter_estagio_estagiario_alter_estagio_orientador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio_app.lab'),
        ),
    ]
