# Generated by Django 4.0.5 on 2022-07-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0003_alter_docente_formacao'),
        ('estagio_app', '0004_alter_estagio_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='estagiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membro_estagiario', to='usuarios_app.discente'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membro_orientador', to='usuarios_app.docente'),
        ),
        migrations.AlterField(
            model_name='estagio',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membro_supervisor', to='usuarios_app.docente'),
        ),
    ]
