# Generated by Django 4.0.5 on 2022-07-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.TextField()),
                ('areaCNPQ', models.CharField(blank=True, max_length=150, null=True)),
                ('subAreaCNPQ', models.CharField(blank=True, max_length=150, null=True)),
                ('laboratorio_pesq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio_pesq', to='laboratorio_app.lab')),
            ],
        ),
    ]
