# Generated by Django 4.0.4 on 2022-07-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhapesquisa_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhapesquisa',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
    ]
