# Generated by Django 4.0.5 on 2022-06-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linhapesquisa_app', '0002_linhapesquisa_laboratorio_pesq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linhapesquisa',
            name='area',
        ),
        migrations.RemoveField(
            model_name='linhapesquisa',
            name='cnpq',
        ),
        migrations.AddField(
            model_name='linhapesquisa',
            name='areaCNPQ',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='linhapesquisa',
            name='subAreaCNPQ',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='linhapesquisa',
            name='descricao',
            field=models.TextField(),
        ),
    ]
