# Generated by Django 4.0.4 on 2022-07-15 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('formacao', models.CharField(max_length=50)),
                ('tipo_jornada_trabalho', models.CharField(max_length=50)),
                ('vinculo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('classe_funcional', models.CharField(max_length=50)),
                ('id_unidade_lotacao', models.IntegerField()),
                ('lotacao', models.CharField(max_length=150)),
                ('admissao', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=15, unique=True)),
                ('nome_discente', models.CharField(max_length=200)),
                ('sexo', models.CharField(blank=True, max_length=1)),
                ('ano_ingresso', models.IntegerField()),
                ('periodo_ingresso', models.IntegerField()),
                ('forma_ingresso', models.CharField(max_length=100)),
                ('tipo_discente', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('sigla_nivel_ensino', models.CharField(max_length=5)),
                ('nivel_ensino', models.CharField(max_length=50)),
                ('id_curso', models.CharField(max_length=100)),
                ('nome_curso', models.CharField(max_length=200)),
                ('modalidade_educacao', models.CharField(max_length=50)),
                ('id_unidade', models.IntegerField()),
                ('nome_unidade', models.CharField(max_length=200)),
                ('id_unidade_gestora', models.IntegerField()),
                ('nome_unidade_gestora', models.CharField(max_length=200)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
