# Generated by Django 4.0.4 on 2022-07-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoGratificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('situacao_servidor', models.CharField(max_length=25)),
                ('id_unidade', models.IntegerField()),
                ('lotacao', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=15)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(null=True)),
                ('id_unidade_designacao', models.IntegerField()),
                ('unidade_designacao', models.CharField(max_length=200)),
                ('atividade', models.CharField(max_length=100)),
                ('observacoes', models.CharField(max_length=500, null=True)),
            ],
            options={
                'unique_together': {('siape', 'id_unidade', 'inicio', 'atividade')},
            },
        ),
    ]
