# Generated by Django 4.0.5 on 2022-07-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorio_app', '0001_initial'),
        ('membros_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('coordenador_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenador_projeto', to='membros_app.membro')),
                ('laboratorio_projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio_projeto', to='laboratorio_app.lab')),
                ('participantes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='membros_app.membro')),
            ],
        ),
    ]
