# Generated by Django 4.0.5 on 2022-07-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0003_alter_docente_formacao'),
        ('projetos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='coordenador_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenador_projeto', to='usuarios_app.docente'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='usuarios_app.discente'),
        ),
    ]
