# Generated by Django 4.0.4 on 2022-05-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membros_app', '0003_alter_membro_laboratorio_alter_membro_membro_perfil'),
        ('laboratorio_app', '0003_alter_lab_coordenador_alter_lab_vice_coordenador'),
        ('projetos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='coordenador',
        ),
        migrations.AddField(
            model_name='projeto',
            name='coordenador_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenador_projeto', to='membros_app.membro'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='laboratorio_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio_projeto', to='laboratorio_app.lab'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='membros_app.membro'),
        ),
    ]
