# Generated by Django 4.0.5 on 2022-06-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_app', '0002_remove_projeto_coordenador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(),
        ),
    ]
