# Generated by Django 4.0.4 on 2022-05-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio_app', '0003_alter_lab_coordenador_alter_lab_vice_coordenador'),
        ('membros_app', '0002_alter_membro_laboratorio_alter_membro_membro_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membro',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio_app.lab'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='membro_perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membros_app.perfil'),
        ),
    ]
