# Generated by Django 4.0.5 on 2022-06-05 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros_app', '0003_alter_membro_laboratorio_alter_membro_membro_perfil'),
        ('linhapesquisa_app', '0002_linhapesquisa_laboratorio_pesq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('dtpublicacao', models.DateField()),
                ('instituicao', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=150)),
                ('autores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorestcc', to='membros_app.membro')),
                ('orientadores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orientadorestcc', to='membros_app.membro')),
                ('pesquisa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesquisa', to='linhapesquisa_app.linhapesquisa')),
            ],
        ),
    ]
