# Generated by Django 4.0.5 on 2022-07-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linhapesquisa_app', '0001_initial'),
        ('membros_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('dtpublicacao', models.DateField()),
                ('instituicao', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('autores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorestcc', to='membros_app.membro')),
                ('orientadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientadorestcc', to='membros_app.membro')),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisa', to='linhapesquisa_app.linhapesquisa')),
            ],
        ),
    ]
