# Generated by Django 4.0.5 on 2022-07-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0003_alter_docente_formacao'),
        ('tcc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcc',
            name='autores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorestcc', to='usuarios_app.discente'),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='orientadores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientadorestcc', to='usuarios_app.docente'),
        ),
    ]
