# Generated by Django 4.0.4 on 2022-07-04 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros_app', '0001_initial'),
        ('artigo_app', '0001_initial'),
        ('laboratorio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='autores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores', to='membros_app.membro'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='laboratorio_art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratorio_art', to='laboratorio_app.lab'),
        ),
    ]
