# Generated by Django 4.0.4 on 2022-05-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=60)),
                ('nome', models.CharField(max_length=60)),
                ('coordenador', models.CharField(max_length=60)),
                ('vice_coordenador', models.CharField(max_length=60)),
            ],
        ),
    ]
