# Generated by Django 4.0.4 on 2022-05-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membros_app', '0001_initial'),
        ('laboratorio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenador', to='membros_app.membro'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='vice_coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_coordenador', to='membros_app.membro'),
        ),
    ]
