# Generated by Django 4.0.5 on 2022-07-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorio_app', '0001_initial'),
        ('membros_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenador', to='membros_app.membro'),
        ),
        migrations.AddField(
            model_name='lab',
            name='vice_coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_coordenador', to='membros_app.membro'),
        ),
    ]
