# Generated by Django 4.0.4 on 2022-05-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membros_app', '0002_alter_membro_laboratorio_alter_membro_membro_perfil'),
        ('laboratorio_app', '0002_alter_lab_coordenador_alter_lab_vice_coordenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenador', to='membros_app.membro'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='vice_coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_coordenador', to='membros_app.membro'),
        ),
    ]
