# Generated by Django 4.0.5 on 2022-07-15 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_app', '0002_funcaogratificada'),
        ('laboratorio_app', '0003_alter_lab_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenador', to='usuarios_app.docente'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='vice_coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vice_coordenador', to='usuarios_app.docente'),
        ),
    ]
