# Generated by Django 4.0.4 on 2022-05-18 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorlabapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
