# Generated by Django 4.0.4 on 2022-07-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento_app', '0001_initial'),
        ('laboratorio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio_app.lab'),
        ),
    ]
