# Generated by Django 4.0.4 on 2022-07-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento_app', '0003_alter_evento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_sbm',
            field=models.DateField(),
        ),
    ]
