# Generated by Django 4.0.5 on 2022-06-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento_app', '0004_alter_evento_descricao_alter_evento_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='site',
            field=models.CharField(max_length=50),
        ),
    ]
