# Generated by Django 4.0.5 on 2022-06-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento_app', '0005_alter_evento_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='site',
            field=models.URLField(),
        ),
    ]
